# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DatingApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DatingApp

  target 'DatingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DatingAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'SDWebImage', '~>3.8'


end
